### ISSUE TITLE
Duplicate data property in config.requirejsPaths

### ISSUE THREAD

**Issue by hakantunc** [webgme/webgme-cli#109]
When a plugin and a seed share a name, configuration for requirejs has duplicate data property.

**Comment by brollb** [comment]
I would recommend people just don't name seeds and plugins w/ the same name... Would you prefer namespacing the components (plugins, etc)?

**Comment by hakantunc** [comment]
Sounds good to me. Users can add prefix or suffix if they want to use the same name.
