### ISSUE TITLE
"enable plugin" command should be either updated or removed

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-cli#116]
Since webgme now adds the plugins by meta type, the `enable plugin` command is now out of date and should be removed.

The README should also be updated.

**Comment by brollb** [comment]
Technically, this command enables the plugin for the meta node... I may leave this functionality but I am not sure...

**Comment by pmeijer** [comment]
It's a separate command right? I pretty sure it's not used that much and wouldn't spend time maintaining it.

**Comment by pmeijer** [comment]
For the readme you could include links to: [GME Plugins](https://github.com/webgme/webgme/wiki/GME-Plugins), [GME Decorators](https://github.com/webgme/webgme/wiki/GME-Decorators), etc.
