### ISSUE TITLE
Add README.md to /config in generated folder

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-cli#117]
webgme-cli should generate a README.md in the `config/` directory explaining the structure of the config and linking to the webgme repo's `config.default.js`

**Comment by brollb** [comment]
How is this for a README.md?

# WebGME Configuration Settings
On `npm start`, the webgme app will load `config.default.js` which will override the configuration [defaults](https://github.com/webgme/webgme/tree/master/config).

If `NODE_ENV` is set, it will first try to load the configuration settings from `config/config.ENV.js` where `ENV` is the value of `NODE_ENV`. For example,
```
NODE_ENV=debug npm start
```
will load the configuration settings from `config/config.debug.js` if it exists and fallback to `config/config.default.js` otherwise

**Comment by pmeijer** [comment]
Can you mention the webgme.config too?

**Comment by pmeijer** [comment]
Btw do you explicitly load the default from the webgme repo (if not there will be issues when NODE_ENV is set).

**Comment by brollb** [comment]
Yeah, I explicitly load `config.default.js` in `config.webgme.js` (the file containing the base overrides for the project).
