### ISSUE TITLE
Uncaught exception when trying to add external components.

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme-cli#119]
Within [logic-gates](https://github.com/webgme/) trying to add a component results in the following exception:

```
C:\GIT\logic-gates>webgme add seed PetriNet webgme/petri-net
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn npm ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by pmeijer** [comment]
I'm using node v0.12.7

**Comment by pmeijer** [comment]
And version 1.5.0 of setup tools

**Comment by brollb** [comment]
I am not getting this error - I think this is a windows problem (I saw a similar problem with running my tests in windows)

**Comment by brollb** [comment]
That being said, this exposed a new issue - mismatched url/package names

**Comment by pmeijer** [comment]
ok I will try it out on my mac

**Comment by brollb** [comment]
Is this still a problem?

**Comment by pmeijer** [comment]
Got the exception with v1.7.0, updating to v1.7.1 now..
