### ISSUE TITLE
Package name mismatch for dependencies

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-cli#120]
When adding packages with mismatched names, the tool parses the url for the project name rather than looking it up in the package.json.

**Comment by brollb** [comment]
Looking up the package name is tricky (when it doesn't match the input name)... I am going to avoid this by adding the following option for github repos with different package.json names:
```
webgme add plugin MyPlugin organization/github_repo --package-name MyWebGMEApp
```

**Comment by lattmann** [comment]
:+1:
