### ISSUE TITLE
Windows paths stored in webgme-setup.json fails on unix.

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme-cli#121]
When depending on a component from a "windows-repo" the adding fails with error due to the windows path separator.

**Comment by brollb** [comment]
@pmeijer Any chance you would want to try writing a test for this? It is tricky for me to replicate right now...

**Comment by pmeijer** [comment]
Do you have a test for adding components from another repo? If so just change the '/' to '\\'.

**Comment by brollb** [comment]
I would rather the `webgme-setup.json` uses a common format. That is, I think the path separator should be corrected before writing to the `webgme-setup.json` and not on read.... I will see if I can write a nice unit test to catch this
