### ISSUE TITLE
webgme-cli fails to install on Ubuntu 14.04LTS

### ISSUE THREAD

**Issue by sprinkjm** [webgme/webgme-cli#200]
On a brand-new vm.

```
webgme@webgme:~$ cd webgme-cli/
webgme@webgme:~/webgme-cli$ ls
bin  extra  LICENSE  package.json  README.md  src  test-src
webgme@webgme:~/webgme-cli$ npm install
npm http GET https://registry.npmjs.org/babel
npm http GET https://registry.npmjs.org/change-case
npm http GET https://registry.npmjs.org/deep-readdir
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/exists-file
npm http GET https://registry.npmjs.org/fs-extra
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/nop
npm http GET https://registry.npmjs.org/plural
npm http GET https://registry.npmjs.org/mongo-uri
npm http GET https://registry.npmjs.org/q
npm http GET https://registry.npmjs.org/npm
npm http GET https://registry.npmjs.org/ramda
npm http GET https://registry.npmjs.org/requirejs
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/chai
npm http GET https://registry.npmjs.org/webgme
npm http GET https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/ejs
npm http GET https://registry.npmjs.org/sinon
npm http GET https://registry.npmjs.org/sinon-chai
npm http GET https://registry.npmjs.org/mocha
npm http GET https://registry.npmjs.org/istanbul
npm http 304 https://registry.npmjs.org/deep-readdir
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/fs-extra
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/nop
npm http 304 https://registry.npmjs.org/babel
npm http 304 https://registry.npmjs.org/plural
npm http 200 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/q
npm http 304 https://registry.npmjs.org/mongo-uri
npm http 304 https://registry.npmjs.org/ramda
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/chai
npm http 304 https://registry.npmjs.org/requirejs
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/webgme
npm http 304 https://registry.npmjs.org/ejs
npm http 304 https://registry.npmjs.org/sinon-chai
npm http 304 https://registry.npmjs.org/sinon
npm http 304 https://registry.npmjs.org/mocha
npm http 304 https://registry.npmjs.org/istanbul
npm http 304 https://registry.npmjs.org/npm
npm http 304 https://registry.npmjs.org/exists-file
npm ERR! git fetch -a origin (git://github.com/brollb/commander.js) error: cannot open FETCH_HEAD: Permission denied
npm ERR! Error: No compatible version found: commander@'brollb/commander.js'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.3","0.0.4","0.0.5","0.1.0","0.2.0","0.2.1","0.3.0","0.3.1","0.3.2","0.3.3","0.4.0","0.4.1","0.4.2","0.4.3","0.5.0","0.5.1","0.6.0","0.6.1","0.5.2","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.1.0","1.1.1","1.2.0","1.3.0","1.3.1","1.3.2","2.0.0","2.1.0","2.2.0","2.3.0","2.4.0","2.5.0","2.5.1","2.6.0","2.7.0","2.7.1","2.8.0","2.8.1","2.9.0"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.2.0-27-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/webgme/webgme-cli
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm http 304 https://registry.npmjs.org/change-case
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/webgme/webgme-cli/npm-debug.log
npm ERR! not ok code 0
webgme@webgme:~/webgme-cli$
```

What if it is an issue of not installing with the correct args?

```
webgme@webgme:~/webgme-cli$ npm install webgme-cli
npm WARN install Refusing to install webgme-cli as a dependency of itself
webgme@webgme:~/webgme-cli$ npm install webgme-cli -g
npm http GET https://registry.npmjs.org/webgme-cli
npm http 304 https://registry.npmjs.org/webgme-cli
npm ERR! error rolling back Error: EACCES, unlink '/usr/local/lib/node_modules/webgme-cli'
npm ERR! error rolling back  webgme-cli@2.2.0 { [Error: EACCES, unlink '/usr/local/lib/node_modules/webgme-cli']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/webgme-cli' }
npm ERR! Error: EACCES, unlink '/usr/local/lib/node_modules/webgme-cli'
npm ERR!  { [Error: EACCES, unlink '/usr/local/lib/node_modules/webgme-cli']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/webgme-cli' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 4.2.0-27-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "webgme-cli" "-g"
npm ERR! cwd /home/webgme/webgme-cli
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/webgme-cli
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, unlink '/usr/local/lib/node_modules/webgme-cli'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/webgme/webgme-cli/npm-debug.log
npm ERR! not ok code 0
webgme@webgme:~/webgme-cli$ 
```

Maybe sudo helps?

```
sudo npm install webgme-cli -g
```

> skipping a lot of output...
> npm http GET https://registry.npmjs.org/wrappy
> npm http 304 https://registry.npmjs.org/core-util-is
> npm http 304 https://registry.npmjs.org/wrappy
> 
> > webgme@2.6.0 postinstall /usr/local/lib/node_modules/webgme-cli/node_modules/webgme
> > bower install && node ./utils/postinstall.js -c jsdoc_conf.json
> 
> bower cached        https://github.com/twbs/bootstrap.git#3.3.7
> bower validate      3.3.7 against https://github.com/twbs/bootstrap.git#3.3.7
> bower cached        https://github.com/twbs/bootstrap.git#3.3.7
> bower validate      3.3.7 against https://github.com/twbs/bootstrap.git#>=2.0.0
> bower cached        https://github.com/twbs/bootstrap.git#3.3.7
> bower validate      3.3.7 against https://github.com/twbs/bootstrap.git#>= 2.3.2
> bower cached        https://github.com/kriskowal/q.git#1.4.1
> bower validate      1.4.1 against https://github.com/kriskowal/q.git#1.4.1
> bower cached        https://github.com/swisnl/jQuery-contextMenu.git#2.2.4
> bower validate      2.2.4 against https://github.com/swisnl/jQuery-contextMenu.git#2.2.4
> bower install       jQuery-contextMenu#2.2.4
> bower skipped       jQuery-contextMenu was not installed because there is already a non-bower directory with that name in the components directory (src/client/bower_components/jQuery-contextMenu). You can force installation with --force.
> bower install       q#1.4.1
> bower skipped       q was not installed because there is already a non-bower directory with that name in the components directory (src/client/bower_components/q). You can force installation with --force.
> bower install       bootstrap#3.3.7
> bower skipped       bootstrap was not installed because there is already a non-bower directory with that name in the components directory (src/client/bower_components/bootstrap). You can force installation with --force.
> 
> jQuery-contextMenu#2.2.4 ../../../../../../../home/webgme/.cache/bower/packages/d0fca6d56cd3826722e59aa6a40ba40f/2.2.4
> └── jquery#2.2.3
> 
> q#1.4.1 ../../../../../../../home/webgme/.cache/bower/packages/eeee04ee15503ebca10a2ea23720ef0e/1.4.1
> 
> bootstrap#3.3.7 ../../../../../../../home/webgme/.cache/bower/packages/478ab1d28ba78f550601bf536eea62f5/3.3.7
> └── jquery#2.2.3
> dist files existed, will not build from postinstall
> /usr/local/bin/webgme -> /usr/local/lib/node_modules/webgme-cli/bin/webgme
> 
> > webgme-cli@2.2.0 postinstall /usr/local/lib/node_modules/webgme-cli
> > node bin/install.js
> 
> 
> /usr/local/lib/node_modules/webgme-cli/bin/install.js:9
> spawnSync('node', [path.join(__dirname, 'build.js'), 'src', 'lib']);
> ^
> TypeError: undefined is not a function
>     at Object.<anonymous> (/usr/local/lib/node_modules/webgme-cli/bin/install.js:9:1)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:902:3
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
>  
> npm ERR! weird error 8
> npm ERR! not ok code 0
> webgme@webgme:~/webgme-cli$

I agree that npm shouldn't really need sudo access, but I don't know how the mechanics to install on the global path to get webgme as a cmd line without it, even if the installer got that far.

I hope this post clarifies why I made posts in other repos to try to understand whether I was meant to be doing this install inside a separate repo, or in a repo in which this is a dependency.

**Comment by brollb** [comment]
It looks like this has the same cause as #199. Could you let me know if that fixes your problem?

**Comment by sprinkjm** [comment]
Will do: I created a new issue only because of the confusion into whether I should be running these commands inside of webgme-cli or instead inside of webgme, and wasn't sure which one you wanted to keep.

**Comment by brollb** [comment]
no problem - ideally these issues, and the conversations associated, can be useful for anyone else with similar questions/problems later, so no complaints here!
