### ISSUE TITLE
add SimpleNodes plugin

### ISSUE THREAD

**Issue by lazydino** [webgme/webgme-cli#213]
I am running webgme-cli version 2.4.0 on Windows 10 to add SimpleNodes plugin using

webgme add plugin SimpleNodes brollb/webgme-simplenodes

but it does not recognize 'add plugin...' option?

![image](https://user-images.githubusercontent.com/1158846/29783081-df6fb774-8bd3-11e7-950a-9451db407574.png)

**Comment by brollb** [comment]
thanks for the detailed issue!

So, as of v2.0.0, the `add` command was renamed to `import` to make it more clear that it was importing the given plugin from another project and not creating a blank one. It looks like the quick start for the webgme-simple-nodes hadn't updated their instructions for webgme-cli v2.x (just updated it so it should be good now).

Let me know if this fixes the issue!

**Comment by lazydino** [comment]
It won't complain now, but I don't seem to able to create with the ExampleModel seed file.. The seed is there in node_modules/webgme-simple-nodes. How would I modify my config file to locate the seed there?

**Comment by lazydino** [comment]
First I create a new webgme project with "webgme init", then I add a simple cusom config/config.mine.js to make the instance access a mongodb server running in another machine
```
'use strict';

var config = require('./config.default');

config.mongo.uri = "mongodb://192.168.1.71:27017/gme001";
module.exports = config;
```

This runs fine with NODE_ENV set to 'mine' and the opening dialog presents me the default seed file selections.
![gmepic001](https://user-images.githubusercontent.com/1158846/29836123-1bb33c30-8ca9-11e7-8c22-c668b7a52896.png)

Now I try 'import' simple-nodes plug-in and see if it could be integrated with this existing project...
```
webgme import plugin SimpleNodes brollb/webgme-simple-nodes
```
I still get the same seed file selections from the opening dialog? What more need to be done to adopt a imported plugin ? I make default seed project to "ExampleModel" like the Simple-Nodes repos, it doesn't work either...
```
'use strict';

var config = require('./config.default');

config.mongo.uri = "mongodb://192.168.1.71:27017/gme001";
config.seedProjects.defaultProject = 'ExampleModel';
config.plugin.allowServerExecution = true;

module.exports = config;
```

**Comment by pmeijer** [comment]
@lazydino I think the missing part is that you need to import the seed from SimpleNodes as well.
```webgme import seed ExampleModel rollb/webgme-simple-nodes```

**Comment by pmeijer** [comment]
Also make sure that you restart your server after the repo has been updated with new components from the webgme-cli.

**Comment by lazydino** [comment]
Thanks! I should have noticed that 'seed' is one of the components, and it is mentioned at readme...
