### ISSUE TITLE
Cannot start webgme on node6.11

### ISSUE THREAD

**Issue by Anirban2404** [webgme/webgme-cli#214]
webgme start
module.js:529
    throw err;
    ^

Error: Cannot find module '../lib/BinUtils'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/webgme-cli/bin/webgme:29:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)

**Comment by brollb** [comment]
How did you install webgme-cli? Did you use `npm install -g webgme-cli`?

**Comment by Anirban2404** [comment]
Yes..I did use `npm install -g webgme-cli`. `npm start` is working fine though.
But, I installed node differently.
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs

**Comment by brollb** [comment]
Can you check the version with `node -v` and the version of npm with `which npm`? If you are installing node from source, you shouldn't need to install it with apt-get also (it could be causing problems).

**Comment by Anirban2404** [comment]
I didn't do any apt-get install.
Command sequence:
`curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -`
`sudo apt-get install -y nodejs`
`npm install -g webgme-cli`
`webgme init`
and got that error.

**Comment by brollb** [comment]
So, basically, the missing files are generated from the source files as the source for webgme-cli includes some ES6 which needs to be transpiled to ES5. They could be missing because the postinstall build failed (at least that is my suspicion) due to an old version of NodeJS being used to install it.

I think the problem is with the `apt-get install` in the second command. If you are installing nodejs from source by downloading the package, you shouldn't need to install it using apt-get as well. I suspect that the version of npm that you are using with `npm` could be using an old version of NodeJS. 

Regardless, I would recommend removing the version of nodejs installed using apt-get and then removing and reinstalling webgme-cli (with only one version of nodejs installed). If you still have problems, can you post the output of the following commands with the next comment?

```
which node
which npm
which webgme

node -v
npm -v
webgme -v
```

And, of course, if there are any build errors when installing webgme-cli, those would be good to include, too!

**Comment by Anirban2404** [comment]
I installed nodeJS as described in https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions.
`curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -`
This script run to prepare the nodeJS package and finally give the output `## Run `apt-get install nodejs` (as root) to install Node.js v6.x and npm
`
Then `sudo apt-get install -y nodejs` installs nodeJS and npm package.
And this is not nodejs/npm issue, because other things are working. Even `npm start` is working to start webgme server without any error.
I didn't get any build error, pasting below"
```
 npm install -g webgme-cli
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/bin/webgme -> /usr/lib/node_modules/webgme-cli/bin/webgme

> webgme-cli@2.4.0 postinstall /usr/lib/node_modules/webgme-cli
> node bin/install.js

Note: Autocomplete for bash can be enabled with:

        echo ". /usr/lib/node_modules/webgme-cli/extra/webgme.completion.bash" >> ~/.bashrc

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/webgme-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ webgme-cli@2.4.0
added 115 packages and updated 1 package in 32.799s
```
when I do webgme start/init/new etc I get that error.

```

# which node
/usr/bin/node
# which npm
/usr/bin/npm
# which webgme
/usr/bin/webgme
# node -v
v6.11.3
# npm -v
5.4.2
# webgme -v
module.js:471
    throw err;
    ^

Error: Cannot find module '../lib/BinUtils'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/webgme-cli/bin/webgme:29:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by brollb** [comment]
@Anirban2404: We took care of this in person, right? If I remember correctly, we uninstalled the webgme-cli then reinstalled it making sure only node v6 was on the system, right?

**Comment by Anirban2404** [comment]
Yes, I forgot to close the issue. Sorry.
