### ISSUE TITLE
webgme start shows no error when dependencies can't be satisfied

### ISSUE THREAD

**Issue by ksmyth** [webgme/webgme-cli#217]
**Environment:** 

***webgme-cli version (`webgme -v`):*** v2.5.0

***Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)*** Windows 10

***NodeJS version (`node -v`):*** v8.9.0

***npm version (`npm -v`):*** 5.5.1

**Description:**

**Steps to Reproduce:**

Put a nonexistent dependency in package.json:

```
"dependencies": {
    "asdfffff": "=12345.0.1"
```

**Results:**

`webgme start` shows `Installing dependencies...` then exits with no other output. It should show that the dependencies can't be satisfied. e.g. `npm install` shows `npm ERR! 404 Not Found: asdfffff@=12345.0.1`

**Comment by brollb** [comment]
How's this?

![deepinscreenshot_select-area_20171109161255](https://user-images.githubusercontent.com/4982789/32632335-df099b50-c568-11e7-8472-0cb147b4fda9.png)
