### ISSUE TITLE
webgme new vizualizer options help menu update

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-cli#233]
**Environment:**
Ubuntu

***webgme-cli version (`webgme -v`):***

***Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)***

***NodeJS version (`node -v`):***

***npm version (`npm -v`):***

**Description:**

**Steps to Reproduce:**
webgme new viz --name chronograph
**Results:**
```
vagrant@vagrant:~/indices/fecbenchstudio/src$ webgme new viz --name chronograph

  Usage: webgme-new-viz [options] <visualizerID>

  Options:

    -h, --help               output usage information
    --name <visualizerName>  Set the visualizer name. Default is the id
    --secondary              Create visualizer not used for active node visualization

vagrant@vagrant:~/indices/fecbenchstudio/src$ webgme new viz chronograph

```

**Comment by brollb** [comment]
This is relatively common practice (check out `npm asd` for an example). The alternative would be to have error messages more like gnu `cp`:
![deepinscreenshot_select-area_20171215113246](https://user-images.githubusercontent.com/4982789/34053256-ae8567b8-e18b-11e7-9b3d-c68560fa21ff.png)

**Comment by brollb** [comment]
As this is provided by the underlying cli library (commanderjs) and is an acceptable way of handling invalid commands, I think the current behavior is acceptable and am reluctant to change it.

That being said, I do not have strong feelings about either way of handling invalid arguments. If anyone else feels strongly towards the `cp`-style error feedback, feel free to open a PR.
