### ISSUE TITLE
config.webgme.js - issue with path generation

### ISSUE THREAD

**Issue by mnag1124** [webgme/webgme-cli#241]
***webgme-cli version 2.7:***

***Windows***

***NodeJS version 8.11.1:***

***npm version5.8.0:***

**Description: requireJS paths that are generated on a windows machine sometimes have a single forward slash instead of double, resulting in an incorrect path.Ensure that the path is always with a backslash **

[files.zip](https://github.com/webgme/webgme-cli/files/1944496/files.zip)

**Comment by brollb** [comment]
Related to #197 but a concrete example. thanks @mnag1124
