### ISSUE TITLE
error with npm package

### ISSUE THREAD

**Issue by ericbaranowski** [webgme/webgme-cli#256]
I get a child process error when installing from npm and running 'webgme init myProject', but when I cloned the repo and published a new version to npm the command seemed to work fine, so can you maybe republish the repo to npm?

**Comment by brollb** [comment]
Thanks for the catch! I am not sure what went wrong on the last release - maybe an issue with the deployment machine? (@pmeijer any thoughts?)

I have republished and verified that the permissions issue has been resolved!
